<?php

namespace app\modules\apv1\models;

use yii\base\Model;
use yii\data\ActiveDataProvider;


/**
 * PostSearch represents the model behind the search form of `app\models\Post`.
 */
class OrdentrabajoSearch extends \app\modules\apv1\models\Ordentrabajo
{
  public $inmueble;
  public $tarea;
  public $supervisor;
  //public $nroorden;
    public function fields()
    {
        return parent::fields(); // TODO: Change the autogenerated stub
    }
//    public function fields()
//    {
//        return ['id','title','comments']; // TODO: Change the autogenerated stub
//    }


    /**
     * {@inheritdoc}
     */
//    public function rules()
//    {
//        return [
////            [['id', 'created_at', 'updated_at', 'created_by', 'updated_by'], 'integer'],
//            [['id','title', 'body','comments'], 'safe'],
//        ];
//    }



    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['id'], 'integer'],
            [['id','nro','inmueble','tarea','fecinicio','descripcion','archivo','supervisor'], 'safe'],
        ];
    }


    /**
     * {@inheritdoc}
     */
//    public function scenarios()
//    {
//        // bypass scenarios() implementation in the parent class
//        return Model::scenarios();
//    }

    /**
     * Creates data provider instance with search query applied
     *
     * @param array $params
     *
     * @return ActiveDataProvider
     */
    public function search($params)
    {
        $query = Ordentrabajo::find();
    //    $query->join('LEFT JOIN', 'post', 'post.user_id = user.id');
        $query->leftJoin( 'tarea', 'ordentrabajo.id_tarea= tarea.id' );
        $query->leftJoin( 'inmueble', 'ordentrabajo.id_inmueble= inmueble.id' );
          $query->innerJoin( 'user', 'public.ordentrabajo.id_supervisor= public.user.id' );
        //$query->joinLeft('tarea');
        //$query->joinWith('');
      //  $query->joinLeft('inmueble');
//        $query->joinWith('comments');

        // add conditions that should always apply here

        $dataProvider = new ActiveDataProvider([
            'query' => $query,
        ]);

        $this->load($params,'');

//        if (!$this->validate()) {
            // uncomment the following line if you do not want to return any records when validation fails
            // $query->where('0=1');
//            return $dataProvider;
//        }

        // grid filtering conditions
        $query->andFilterWhere(['id' => $this->id]);

        $query->andFilterWhere(['like','inmueble.nombre',$this->inmueble]);
        $query->andFilterWhere(['like','tarea.nombre',$this->tarea]);
        $query->andFilterWhere(['like','public.user.username',$this->supervisor]);
        $query->andFilterWhere(['like','fecinicio',$this->fecinicio]);
        $query->andFilterWhere(['like','descripcion',$this->descripcion]);



        return $dataProvider;
    }
}
