<?php

namespace app\modules\apv1\models;

use yii\base\Model;
use yii\data\ActiveDataProvider;


/**
 * PostSearch represents the model behind the search form of `app\models\Post`.
 */
class ResponsableSearch extends \app\modules\apv1\models\Responsable
{
  public $usuario;
  public $ordentrabajo;
  //public $nroorden;
    public function fields()
    {
        return parent::fields(); // TODO: Change the autogenerated stub
    }
//    public function fields()
//    {
//        return ['id','title','comments']; // TODO: Change the autogenerated stub
//    }


    /**
     * {@inheritdoc}
     */
//    public function rules()
//    {
//        return [
////            [['id', 'created_at', 'updated_at', 'created_by', 'updated_by'], 'integer'],
//            [['id','title', 'body','comments'], 'safe'],
//        ];
//    }



    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['id'], 'integer'],
            [['id','usuario','ordentrabajo'], 'safe'],
        ];
    }


    /**
     * {@inheritdoc}
     */
//    public function scenarios()
//    {
//        // bypass scenarios() implementation in the parent class
//        return Model::scenarios();
//    }

    /**
     * Creates data provider instance with search query applied
     *
     * @param array $params
     *
     * @return ActiveDataProvider
     */
    public function search($params)
    {
        $query = Responsable::find();
        $query->innerJoin( 'user', 'public.responsable.id_usuario= public.user.id' );
        $query->innerJoin( 'ordentrabajo', 'responsable.id_ordentrabajo= ordentrabajo.id' );
        // add conditions that should always apply here

        $dataProvider = new ActiveDataProvider([
            'query' => $query,
        ]);

        $this->load($params,'');

//        if (!$this->validate()) {
            // uncomment the following line if you do not want to return any records when validation fails
            // $query->where('0=1');
//            return $dataProvider;
//        }

        // grid filtering conditions
        $query->andFilterWhere(['id' => $this->id]);
        $query->andFilterWhere(['like','user.username',$this->usuario]);
        $query->andFilterWhere(['like','ordentrabajo.nro',$this->ordentrabajo]);



        return $dataProvider;
    }
}
