version: "3.1"

services:

  db:
    image: postgres:9.5
    environment:
      POSTGRES_DB: justicia2020
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: justicia2020

    ports:
          - 5433:5432
    volumes:
            - ./postgressqldata:/var/lib/postgresql/data:delegated

  phppgadmin:
    image: dockage/phppgadmin
    environment:
      PHP_PG_ADMIN_SERVER_HOST: db
      PHP_PG_ADMIN_SERVER_PORT: 5432
    ports:
      - 8001:80

  app:
    image: yiisoftware/yii2-php:7.1-apache
    volumes:
      - ./src/composer/cache:/root/.composer/cache:delegated
      - ./src/basic:/app:delegated
    environment:
      DB_DATABASE: justicia2020
      DB_PASSWORD: justicia2020
      DB_HOST: db
      PRODUCCION: 0
      PHP_ENABLE_XDEBUG: 1
      PHP_USER_ID: 1000

    ports:
      - 8000:80
